/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/drvota.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export default function Model(props) {
  const { nodes, materials } = useGLTF('/drvota.glb')
  useFrame(({ clock, camera }) => {
    const elapsedTime = clock.getElapsedTime();
    const radius = 10; // Define the radius of the circular path
    camera.position.x = radius * Math.cos(elapsedTime);
    camera.position.z = radius * Math.sin(elapsedTime);
    camera.lookAt(0, 0, 0); // Make the camera always look at the center of the scene
  });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} rotation={[0,-Math.PI/4,0]} scale={5} position={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/drvota.glb')
